modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPL 3.0"

[[mods]]
modId = "photomode"
version = "${version}"
displayName = "Photo Mode"
authors = ""
description = '''
This mod adds an isometric view of the world dedicated for taking pictures.
Ported with permission from Better than Adventure!
'''
#logoFile = ""

[[dependencies.photomode]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.photomode]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.photomode]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,)"
ordering = "AFTER"
side = "BOTH"