modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/forkiesassds/PhotoMode/issues"
license = "LGPL 3.0"

[[mods]]
modId = "photomode"
version = "${version}"
displayName = "Photo Mode"
authors = ""
description = '''
This mod adds an isometric view of the world dedicated for taking pictures.
Ported with permission from Better than Adventure!
'''
#logoFile = ""

[[dependencies.photomode]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.photomode]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "CLIENT"