# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

minecraft_version=24w21b
#enabled_platforms=fabric,neoforge
enabled_platforms=fabric

mod_version=1.0
maven_group=me.icanttellyou.mods
archives_base_name=PhotoMode

fabric_loader_version=0.15.11
fabric_api_version=0.99.1+1.21

neoforge_version=20.5.0-beta