# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Bypass loom version requirements, needed for FAPI.
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=25w09b
#enabled_platforms=fabric,neoforge
enabled_platforms=fabric

mod_version=1.0
maven_group=me.icanttellyou.mods
archives_base_name=PhotoMode

fabric_loader_version=0.16.10
fabric_api_version=0.118.1+1.21.5

neoforge_version=21.4.89-beta