# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

minecraft_version=25w07a
#enabled_platforms=fabric,neoforge
enabled_platforms=fabric

mod_version=1.0
maven_group=me.icanttellyou.mods
archives_base_name=PhotoMode

fabric_loader_version=0.16.10
fabric_api_version=0.116.1+1.21.5

neoforge_version=21.4.89-beta