modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://codeberg.org/icanttellyou/PictureMode/issues"
license = "MIT"

[[mixins]]
config = "picturemode-common.mixins.json"

[[mods]]
modId = "picturemode"
version = "${version}"
displayName = "Picture Mode"
displayURL = "https://modrinth.com/project/picture-mode"
authors = "icanttellyou"
credits = "Bestsoft100"
description = '''
This mod adds an isometric view of the world dedicated for taking pictures.
Inspired by the Photo Mode from Better than Adventure!
'''
logoFile = "assets/picturemode/banner.png"

[[dependencies.picturemode]]
modId = "${loader}"
mandatory = true
versionRange = "${forgelike_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.picturemode]]
modId = "minecraft"
mandatory = true
versionRange = "${forgelike_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.picturemode]]
modId = "yet_another_config_lib_v3"
mandatory = false
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
